config/routes.rb
Rails.application.routes.draw do
  resources :todos
  root 'todos#index'

  post '/todo' => 'todos#create'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  include TodosHelper
  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
    # sync_update @todos

  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new


  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    # if request.xhr?
    #   if params[:update].nil?
    #     p params
    #     @todo = TodosHelper.add_task(params)
    #     render '_item', layout: false
    #   else
    #     @item_update = TodosHelper.update_task(params)
    #     render json: @item_update
    #   end
    # else

      # @todo = Todo.new(params)
      @todo = TodosHelper.add_task(params)

      respond_to do |format|
        if @todo.save
          p @todo
          p 'before sync'
          sync_new @todo
          p 'after sync'
          format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
          format.json { render :show, status: :created, location: @todo }
        else
          format.html { render :new }
          format.json { render json: @todo.errors, status: :unprocessable_entity }
        end
      end
    # end
   end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/todos_helper.rb
module TodosHelper
	def self.add_task(params)
  	return Todo.create(title: params[:task], active: true)
	end

	def self.update_task(params)
		p "i am in update module"
		@item = Todo.find(params[:item])
		p params[:item]
		p params[:active]
		@item.active = params[:active]
		return @item.save
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag Sync.adapter_javascript_url %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/_item.html.erb
<div class="item=<%= @todo.id%> item_div">
  <%= check_box("item=", @todo.id, {checked: false, :style => "float:left;", class: 'check_box'}) %>
  <%= label @todo.id, @todo.title, @todo.complete, class: 'form-control'  %>
</div>		

app/views/todos/_list_items.html.erb
<div class="center jumbotron task_main">
<h1>ToDo's</h1>
    <div class="form-group">

      <%= text_field_tag 'task', nil, class: 'form-control',placeholder: "What needs to be done?" %>
      <div class="todo_list">
      <% @todos.each do |todo| %>
        <div class="item=<%= todo.id %> item_div">
          <%= check_box("item", todo.id, {checked: todo.active, :style => "float:left;", class: 'check_box'}) %>
          <%= label todo.id, todo.title, todo.complete, class: 'form-control'  %>
        </div>
      <% end %>
      <%= sync_new partial: 'todo_list_row', resource: Todo.new %>
      </div>
    </div>
</div>

app/views/todos/_save.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Todos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.title %></td>
        <td><%= todo.notes %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<br>


<%= render partial: 'list_items' %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @todo.notes %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>